[package]
name = "aoc23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10"
simple_logger = "4.3"
log = "0.4"
itertools = "0.12"
indexmap = "2.1"